saveas(1,'Ventilation factor u.jpg')
saveas(2,'Shading factor v.jpg')
saveas(3,'Backup energy obtained from different starting points.jpg')
saveas(4,'Backup energy obtained from different methods.jpg')
saveas(5,'Running times of different methods.jpg')
saveas(6,'Ventilation factor u and Shading factor v with the air flow rates constraint.jpg')
saveas(7,'All 4 states with the air flow rates constraint.jpg')
saveas(8,'Mass flow m with the air flow rates constraint.jpg')
saveas(9,'Ventilation factor u obtained in Task 2-6.jpg')
saveas(10,'Shading factor v obtained in Task 2-6.jpg')
